name: statschat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript.ttf
    - family: Comforter
      fonts:
        - asset: fonts/Comforter.ttf
    - family: Satisfy
      fonts:
        - asset: fonts/SatisfyRegular.ttf

  assets:
    - images/
